version: '3.8'
services:
  app:
    image: python:3.8-slim
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env
    command: >
      sh -c "pip install -r packages.txt
      && flask run"
    ports:
      - "5000:5000"
    networks:
      - midianitas
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - midianitas
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - midianitas
    depends_on:
      - postgres
      
volumes:
  db_data:
  pgadmin_data:

networks:
  midianitas:
    external: true
  